/** English UI labels keyed by field name (logic keys stay camelCase in code). */
const FIELD_LABELS: Record<string, string> = {
  id: 'ID',
  name: 'Name',
  code: 'Code',
  slug: 'Slug',
  status: 'Status',
  isActive: 'Active',
  sortOrder: 'Sort order',
  description: 'Description',
  icon: 'Icon',
  type: 'Type',
  color: 'Color',
  note: 'Note',
  key: 'Key',
  value: 'Value',
  group: 'Group',
  isEncrypted: 'Encrypted',

  countryId: 'Country',
  countryName: 'Country',
  carrierId: 'Carrier',
  carrierBrand: 'Carrier brand',
  publisherBrand: 'Publisher',
  denominationId: 'Denomination',
  productType: 'Product type',
  productId: 'Product',
  productCode: 'Product code',
  productName: 'Product',
  currencyCode: 'Currency',
  originalPrice: 'Original price',
  salePrice: 'Sale price',
  discountRate: 'Discount rate',
  discountType: 'Discount type',
  discountValue: 'Discount value',
  startDate: 'Start date',
  endDate: 'End date',
  faceValue: 'Face value',
  maxQuantity: 'Max quantity',
  dataAmount: 'Data amount',
  dataUnit: 'Data unit',
  validityDays: 'Validity (days)',
  isUnlimited: 'Unlimited data',
  support5G: '5G support',
  supportHotspot: 'Hotspot support',
  hasPhoneNumber: 'Includes phone number',
  activationMethod: 'Activation method',
  price: 'Price',
  question: 'Question',
  answer: 'Answer',
  targetType: 'Target type',
  targetId: 'Target',
  tagIds: 'Tags',

  providerId: 'Provider',
  providerName: 'Provider',
  providerType: 'Provider type',
  providerProductCode: 'Provider product code',
  providerProductName: 'Provider product name',
  providerProductId: 'Provider product',
  priority: 'Priority',
  balance: 'Balance',
  costPrice: 'Cost price',
  stockStatus: 'Stock status',
  localProductType: 'Local product type',
  localProductId: 'Local product',
  isBackup: 'Backup mapping',
  baseUrl: 'Base URL',
  apiKey: 'API key',
  secretKey: 'Secret key',
  timeoutSeconds: 'Timeout (seconds)',
  sandboxMode: 'Sandbox mode',
  available: 'In stock',
  checkedAt: 'Checked at',
  endpoint: 'Endpoint',
  requestBody: 'Request body',
  responseBody: 'Response body',
  statusCode: 'Status code',
  errorMessage: 'Error message',

  orderNo: 'Order no.',
  orderId: 'Order',
  orderItemId: 'Order item',
  orderStatus: 'Order status',
  customerId: 'Customer',
  customerName: 'Customer',
  totalAmount: 'Total amount',
  paymentStatus: 'Payment status',
  paymentMethod: 'Payment method',
  expiredAt: 'Expires at',
  processingStartedAt: 'Processing started',
  errorReason: 'Error reason',
  lastProviderResponse: 'Last provider response',
  assignedStaff: 'Assigned staff',
  transactionCode: 'Transaction code',
  provider: 'Payment gateway',
  amount: 'Amount',
  paidAt: 'Paid at',
  merchantId: 'Merchant ID',
  iconUrl: 'Icon URL',
  feePercent: 'Fee (%)',
  rawPayload: 'Raw payload',
  signatureValid: 'Valid signature',
  processStatus: 'Process status',
  receivedAt: 'Received at',
  reason: 'Reason',
  approvedBy: 'Approved by',
  refundedAt: 'Refunded at',
  deliveryType: 'Delivery type',
  deliveryId: 'Delivery',
  sentAt: 'Sent at',
  iccid: 'ICCID',
  qrCodeUrl: 'QR code URL',
  activationCode: 'Activation code',
  serial: 'Serial',
  pinCode: 'PIN',
  action: 'Action',
  request: 'Request',
  response: 'Response',

  fullName: 'Full name',
  email: 'Email',
  phone: 'Phone',
  createdAt: 'Created at',
  createdBy: 'Created by',
  lastLoginAt: 'Last login',

  title: 'Title',
  thumbnailUrl: 'Thumbnail URL',
  summary: 'Summary',
  content: 'Content',
  publishedAt: 'Published at',
  seoTitle: 'SEO title',
  seoDescription: 'SEO description',
  seoKeywords: 'SEO keywords',
  canonicalUrl: 'Canonical URL',
  schemaJson: 'Schema (JSON)',
  contentHtml: 'Content (HTML)',
  imageDesktopUrl: 'Desktop image URL',
  imageMobileUrl: 'Mobile image URL',
  linkUrl: 'Link URL',
  position: 'Position',
  fileName: 'File name',
  url: 'URL',
  mimeType: 'MIME type',
  size: 'Size',
  folder: 'Folder',
  pageKey: 'Page key',

  maxUsage: 'Max uses',
  usedCount: 'Times used',
  bodyHtml: 'Body (HTML)',
  variables: 'Variables',
  templateCode: 'Template',
  toEmail: 'Recipient email',
  retryCount: 'Retry count',
  scheduledAt: 'Scheduled at',
  subject: 'Subject',

  userId: 'User',
  userEmail: 'User',
  entityName: 'Entity',
  entityId: 'Entity record',
  oldValue: 'Previous value',
  newValue: 'New value',

  englishName: 'English name',
  isoCode: 'ISO code',
  flagEmoji: 'Flag',
  regionCode: 'Region',
  bannerUrl: 'Banner URL',
  logoUrl: 'Logo URL',
  brandColor: 'Brand color',
  websiteUrl: 'Website',
  brandName: 'Brand',
  deviceName: 'Device',
  modelCode: 'Model code',
  supportEsim: 'eSIM support',
  displayName: 'Display name',
  coverageNote: 'Coverage note',

  date: 'Date',
  revenue: 'Revenue',
  paidOrders: 'Paid orders',
  refundAmount: 'Refunds',
  netRevenue: 'Net revenue',
  soldQty: 'Units sold',
  soldCount: 'Units sold',
  newCustomers: 'New customers',
  successRate: 'Success rate',
  failedCount: 'Failed count',
  error: 'Error',
  module: 'Module',
}

function humanizeFieldName(name: string): string {
  const base = name.endsWith('Id') ? name.slice(0, -2) : name
  const spaced = base
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .trim()
  if (!spaced) return name
  return spaced.charAt(0).toUpperCase() + spaced.slice(1)
}

export function getFieldLabel(fieldName: string): string {
  return FIELD_LABELS[fieldName] ?? humanizeFieldName(fieldName)
}
