import type { Carrier } from '@/views/settings/types'

export const carriersData: Carrier[] = [
  {
    id: 1,
    name: 'SoftBank',
    slug: 'softbank-jp',
    countryId: 1,
    countryName: 'Nhật Bản',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/SoftBank_Mobile_logo.svg',
    support5G: true,
    coverageNote: 'Phủ sóng đô thị lớn, hỗ trợ 5G',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    name: 'NTT Docomo',
    slug: 'docomo-jp',
    countryId: 1,
    countryName: 'Nhật Bản',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/NTT_Docomo_logo.svg',
    support5G: true,
    coverageNote: 'Mạng lớn nhất Nhật Bản',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 3,
    name: 'SK Telecom',
    slug: 'sk-telecom-kr',
    countryId: 2,
    countryName: 'Hàn Quốc',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/SK_Telecom_Logo.svg',
    support5G: true,
    coverageNote: '5G nationwide',
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 4,
    name: 'AIS',
    slug: 'ais-th',
    countryId: 3,
    countryName: 'Thái Lan',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/AIS_logo.svg',
    support5G: false,
    coverageNote: '4G/LTE phổ biến',
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 5,
    name: 'Singtel',
    slug: 'singtel-sg',
    countryId: 4,
    countryName: 'Singapore',
    logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8c/Singtel_logo.svg',
    support5G: true,
    coverageNote: 'Đảo quốc Sư tử',
    sortOrder: 5,
    isActive: false,
  },
]

export const carriersLabels = {
  searchPlaceholder: 'Tìm nhà mạng, quốc gia...',
  addButton: 'Thêm nhà mạng',
  emptyMessage: 'Chưa có nhà mạng nào',
  itemName: 'nhà mạng',
} as const
