import type { Country } from '@/views/settings/types'

export const countriesData: Country[] = [
  {
    id: 1,
    name: 'Nhật Bản',
    englishName: 'Japan',
    slug: 'nhat-ban',
    isoCode: 'JP',
    flagEmoji: '🇯🇵',
    regionCode: 'ASIA',
    bannerUrl: '',
    seoTitle: 'eSIM Nhật Bản - DTP',
    seoDescription: 'Gói eSIM du lịch Nhật Bản, kích hoạt nhanh',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    name: 'Hàn Quốc',
    englishName: 'South Korea',
    slug: 'han-quoc',
    isoCode: 'KR',
    flagEmoji: '🇰🇷',
    regionCode: 'ASIA',
    bannerUrl: '',
    seoTitle: 'eSIM Hàn Quốc',
    seoDescription: 'Data 4G/5G Hàn Quốc cho du khách',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 3,
    name: 'Thái Lan',
    englishName: 'Thailand',
    slug: 'thai-lan',
    isoCode: 'TH',
    flagEmoji: '🇹🇭',
    regionCode: 'ASIA',
    bannerUrl: '',
    seoTitle: 'eSIM Thái Lan',
    seoDescription: 'Gói data Thái Lan giá tốt',
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 4,
    name: 'Singapore',
    englishName: 'Singapore',
    slug: 'singapore',
    isoCode: 'SG',
    flagEmoji: '🇸🇬',
    regionCode: 'ASIA',
    bannerUrl: '',
    seoTitle: 'eSIM Singapore',
    seoDescription: 'Roaming Singapore',
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 5,
    name: 'Việt Nam',
    englishName: 'Vietnam',
    slug: 'viet-nam',
    isoCode: 'VN',
    flagEmoji: '🇻🇳',
    regionCode: 'ASIA',
    bannerUrl: '',
    seoTitle: 'eSIM Việt Nam',
    seoDescription: 'Gói data trong nước',
    sortOrder: 5,
    isActive: false,
  },
]

export const countriesLabels = {
  searchPlaceholder: 'Tìm tên, mã ISO, khu vực...',
  addButton: 'Thêm quốc gia',
  emptyMessage: 'Chưa có quốc gia nào',
  itemName: 'quốc gia',
} as const
