/** Nhãn UI tiếng Việt theo tên field (key logic vẫn camelCase trong code). */
const FIELD_LABELS: Record<string, string> = {
  id: 'ID',
  name: 'Tên',
  code: 'Mã',
  slug: 'Slug',
  status: 'Trạng thái',
  isActive: 'Trạng thái',
  sortOrder: 'Thứ tự',
  description: 'Mô tả',
  icon: 'Icon',
  type: 'Loại',
  color: 'Màu',
  note: 'Ghi chú',
  key: 'Key',
  value: 'Giá trị',
  group: 'Nhóm',
  isEncrypted: 'Mã hóa',

  countryId: 'Quốc gia',
  countryName: 'Quốc gia',
  carrierId: 'Nhà mạng',
  carrierBrand: 'Thương hiệu nhà mạng',
  publisherBrand: 'Nhà phát hành',
  denominationId: 'Mệnh giá',
  productType: 'Loại sản phẩm',
  productId: 'ID sản phẩm',
  productCode: 'Mã SP',
  productName: 'Sản phẩm',
  currencyCode: 'Tiền tệ',
  originalPrice: 'Giá gốc',
  salePrice: 'Giá bán',
  discountRate: 'Chiết khấu (%)',
  discountType: 'Loại giảm',
  discountValue: 'Giá trị giảm',
  startDate: 'Từ ngày',
  endDate: 'Đến ngày',
  faceValue: 'Giá trị',
  maxQuantity: 'Số lượng tối đa',
  dataAmount: 'Dung lượng',
  dataUnit: 'Đơn vị',
  validityDays: 'Số ngày',
  isUnlimited: 'Không giới hạn',
  support5G: 'Hỗ trợ 5G',
  supportHotspot: 'Phát hotspot',
  hasPhoneNumber: 'Có số điện thoại',
  activationMethod: 'Cách kích hoạt',
  price: 'Giá',
  question: 'Câu hỏi',
  answer: 'Trả lời',
  targetType: 'Loại đối tượng',
  targetId: 'ID đối tượng',
  tagIds: 'Tag',

  providerId: 'Nhà cung cấp',
  providerName: 'Nhà cung cấp',
  providerType: 'Loại provider',
  providerProductCode: 'Mã SP provider',
  providerProductName: 'Tên SP provider',
  providerProductId: 'ID SP provider',
  priority: 'Ưu tiên',
  balance: 'Số dư',
  costPrice: 'Giá vốn',
  stockStatus: 'Tình trạng kho',
  localProductType: 'Loại SP local',
  localProductId: 'ID SP local',
  isBackup: 'Dự phòng',
  baseUrl: 'Base URL',
  apiKey: 'API Key',
  secretKey: 'Secret Key',
  timeoutSeconds: 'Timeout (giây)',
  sandboxMode: 'Sandbox',
  available: 'Còn hàng',
  checkedAt: 'Thời điểm kiểm tra',
  endpoint: 'Endpoint',
  requestBody: 'Request body',
  responseBody: 'Response body',
  statusCode: 'Mã trạng thái',
  errorMessage: 'Lỗi',

  orderNo: 'Mã đơn',
  orderId: 'ID đơn hàng',
  orderItemId: 'ID item đơn',
  orderStatus: 'Trạng thái đơn',
  customerId: 'ID khách hàng',
  customerName: 'Khách hàng',
  totalAmount: 'Tổng tiền',
  paymentStatus: 'Trạng thái thanh toán',
  paymentMethod: 'Phương thức TT',
  expiredAt: 'Hết hạn lúc',
  processingStartedAt: 'Bắt đầu xử lý lúc',
  errorReason: 'Lý do lỗi',
  lastProviderResponse: 'Phản hồi provider',
  assignedStaff: 'Nhân viên xử lý',
  transactionCode: 'Mã giao dịch',
  provider: 'Cổng thanh toán',
  amount: 'Số tiền',
  paidAt: 'Thời gian thanh toán',
  merchantId: 'Merchant ID',
  iconUrl: 'Icon URL',
  feePercent: 'Phí (%)',
  rawPayload: 'Raw payload',
  signatureValid: 'Chữ ký hợp lệ',
  processStatus: 'Trạng thái xử lý',
  receivedAt: 'Thời gian nhận',
  reason: 'Lý do',
  approvedBy: 'Người duyệt',
  refundedAt: 'Thời gian hoàn',
  deliveryType: 'Loại giao hàng',
  deliveryId: 'ID giao hàng',
  sentAt: 'Thời gian gửi',
  iccid: 'ICCID',
  qrCodeUrl: 'URL QR code',
  activationCode: 'Mã kích hoạt',
  serial: 'Serial',
  pinCode: 'PIN',
  action: 'Hành động',
  request: 'Request',
  response: 'Response',

  fullName: 'Họ tên',
  email: 'Email',
  phone: 'SĐT',
  createdAt: 'Ngày tạo',
  createdBy: 'Người tạo',
  lastLoginAt: 'Đăng nhập cuối',

  title: 'Tiêu đề',
  thumbnailUrl: 'Ảnh thumbnail',
  summary: 'Tóm tắt',
  content: 'Nội dung',
  publishedAt: 'Ngày đăng',
  seoTitle: 'SEO title',
  seoDescription: 'SEO description',
  seoKeywords: 'SEO keywords',
  canonicalUrl: 'Canonical URL',
  schemaJson: 'Schema JSON',
  contentHtml: 'Nội dung (HTML)',
  imageDesktopUrl: 'Ảnh desktop',
  imageMobileUrl: 'Ảnh mobile',
  linkUrl: 'Link',
  position: 'Vị trí',
  fileName: 'Tên file',
  url: 'URL',
  mimeType: 'MIME type',
  size: 'Dung lượng',
  folder: 'Thư mục',
  pageKey: 'Page key',

  maxUsage: 'Số lượt tối đa',
  usedCount: 'Đã dùng',
  bodyHtml: 'Nội dung (HTML)',
  variables: 'Biến',
  templateCode: 'Mã template',
  toEmail: 'Email nhận',
  retryCount: 'Số lần thử lại',
  scheduledAt: 'Lên lịch lúc',
  subject: 'Tiêu đề',

  userId: 'ID người dùng',
  userEmail: 'Người dùng',
  entityName: 'Đối tượng',
  entityId: 'ID đối tượng',
  oldValue: 'Giá trị cũ',
  newValue: 'Giá trị mới',

  englishName: 'Tên tiếng Anh',
  isoCode: 'Mã ISO',
  flagEmoji: 'Cờ (emoji)',
  regionCode: 'Khu vực',
  bannerUrl: 'URL banner',
  logoUrl: 'URL logo',
  brandColor: 'Màu thương hiệu',
  websiteUrl: 'Website',
  brandName: 'Hãng',
  deviceName: 'Tên thiết bị',
  modelCode: 'Mã model',
  supportEsim: 'Hỗ trợ eSIM',
  displayName: 'Tên hiển thị',
  coverageNote: 'Ghi chú phủ sóng',

  date: 'Ngày',
  revenue: 'Doanh thu',
  paidOrders: 'Đơn đã thanh toán',
  refundAmount: 'Hoàn tiền',
  netRevenue: 'Thực nhận',
  soldQty: 'Đã bán',
  soldCount: 'Đã bán',
  newCustomers: 'Khách mới',
  successRate: 'Tỷ lệ thành công (%)',
  failedCount: 'Số lỗi',
  error: 'Lỗi',
  module: 'Module',
}

function humanizeFieldName(name: string): string {
  const base = name.endsWith('Id') ? name.slice(0, -2) : name
  const spaced = base
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1 $2')
    .trim()
  if (!spaced) return name
  return spaced.charAt(0).toUpperCase() + spaced.slice(1)
}

export function getFieldLabel(fieldName: string): string {
  return FIELD_LABELS[fieldName] ?? humanizeFieldName(fieldName)
}
